{% set name = "slackbot" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94a026738096b5aa6a6e98bfc230594e3d9a11278fbc910583f613cd7a8e2ca5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python
    - pip
    - request
    - websocket-client >=0.22.0,<=0.44.0
    - slacker
    - six
  run:
    - python
    - request
    - websocket-client >=0.22.0,<=0.44.0
    - slacker
    - six

test:
  imports:
    - slackbot

about:
  home: https://github.com/lins05/slackbot
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A simple chat bot for Slack'

extra:
  recipe-maintainers:
    - hadim
